config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  devise_scope :user do
    get 'new_assignment', to: 'users/registrations#new_assignment'
    post 'create_assignment', to: 'users/registrations#create_assignment'
  end
  root 'tops#index'
  resources :messages, only: [:index, :new, :create, :show]
  resources :circulations, only: [:index, :new, :create, :show]
  resources :notices, only: [:index, :new, :create, :show]
  resources :events
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :title, :content, :importancy, :emergency, presence: true
  enum importancy:{
    高:1,中:2,低:3
  }, _prefix: :importancy
  enum emergency:{
    高:1,中:2,低:3
  }, _prefix: :emergency
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end

  def new
    @message = Message.new
  end

  def create
    message = {}
    if message_params[:upload_file].present?
      message_params[:upload_file].read
      message_params[:upload_file_name] = message_params[:upload_file].original_filename
      # message[:upload_file_name] = "#{message_params[:upload_file_name]}.#{message_params[:upload_file].original_filename.split('.')[1]}"
    end
    @message = Message.new(message_params)
    @message.save!
    redirect_to root_path
  end

  private
  
  def message_params
    params.require(:message).permit(:title, :content, :importancy, :emergency, :upload_file_name, :upload_file).merge(user_id: current_user.id)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.haml
.message-index
  .message-index__blank
  .message-index__btn
    =link_to new_message_path, class: "message-index__btn--sentence" do
      %i.far.fa-paper-plane
      新規メッセージを作成
  .message-index__blank
  .message-index__list
    メッセージ一覧

app/views/messages/new.html.haml
.message-new
  .message-new__first
    分かり易く、丁寧に、相手の立場になって、メッセージを作成しましょう。
  .message-new__format
    = form_with model: @message, local: true, multiple: true do |f|
      .field
        = f.label :件名：, class: "field--label"
        = f.label :必須, class: "field--must"
        %br
        = f.text_field :title, autofocus: true, autocomplete: "title", required: "true", class: "field--form--title"
      .field
        = f.label :重要度：, class: "field--label"
        = f.label :必須, class: "field--must"
        %br
        %br
        = f.radio_button :importancy, "高"
        = f.label :高, class: "field--radio--high"
        = f.radio_button :importancy, "中"
        = f.label :中, class: "field--radio--midium"
        = f.radio_button :importancy, "低"
        = f.label :低, class: "field--radio--low"
      .field
        = f.label :緊急度：, class: "field--label"
        = f.label :必須, class: "field--must"
        %br
        %br
        = f.radio_button :emergency, "高"
        = f.label :高, class: "field--radio--high"
        = f.radio_button :emergency, "中"
        = f.label :中, class: "field--radio--midium"
        = f.radio_button :emergency, "低"
        = f.label :低, class: "field--radio--low"
      .field-content
        = f.label :内容：, class: "field-content--label"
        = f.label :必須, class: "field-content--must"
        %br
        = f.text_area :content, autofocus: true, autocomplete: "content", required: "true", class: "field-content--form--content"
      .field-file
        = f.label :添付ファイル：, class: "field-file--label"
        %br
        %br
        = f.file_field :upload_file, class: "field-file--form"
      .submit
        = f.submit "送信", class: "submit--btn"