config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  devise_scope :user do
    get 'new_assignment', to: 'users/registrations#new_assignment'
    post 'create_assignment', to: 'users/registrations#create_assignment'
  end
  root 'tops#index'
  resources :messages, only: [:index, :new, :create, :show]
  resources :circulations, only: [:index, :new, :create, :show]
  resources :notices, only: [:index, :new, :create, :show]
  resources :events
end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :user
  validates :ntc_title, :ntc_content, :ntc_importancy, :ntc_emergency, presence: true
  enum importancy:{
    高:1,中:2,低:3
  }, _prefix: :ntc_importancy
  enum emergency:{
    高:1,中:2,低:3
  }, _prefix: :ntc_emergency
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  def index
  end

  def new
    @notice = Notice.new
  end

  def create
    # notice = {}
    if notice_params[:ntc_upload_file].present?
      notice_params[:ntc_upload_file].read
      notice_params[:ntc_upload_file_name] = notice_params[:ntc_upload_file].original_filename
      # notice[:ntc_upload_file_name] = "#{notice_params[:ntc_upload_file_name]}.#{notice_params[:ntc_upload_file].original_filename.split('.')[1]}"
    end
    @notice = notice.new(notice_params)
    @notice.save!
    redirect_to root_path
  end

  private
  
  def notice_params
    params.require(:notice).permit(:ntc_title, :ntc_content, :ntc_importancy, :ntc_emergency, :ntc_upload_file_name, :ntc_upload_file).merge(user_id: current_user.id)
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/index.html.haml
.notice-index
  .notice-index__blank
  .notice-index__btn
    =link_to new_notice_path, class: "notice-index__btn--sentence" do
      %i.far.fa-paper-plane
      新規お知らせを作成
  .notice-index__blank
  .notice-index__list
    お知らせ一覧

app/views/notices/new.html.haml
.notice-new
  .notice-new__first
    必要な情報をお知らせしましょう。
  .notice-new__format
    = form_with model: @notice, local: true, multiple: true do |f|
      .field
        = f.label :件名：, class: "field--label"
        = f.label :必須, class: "field--must"
        %br
        = f.text_field :ntc_title, autofocus: true, autocomplete: "ntc_title", required: "true", class: "field--form--title"
      .field
        = f.label :重要度：, class: "field--label"
        = f.label :必須, class: "field--must"
        %br
        %br
        = f.radio_button :ntc_importancy, "高"
        = f.label :高, class: "field--radio--high"
        = f.radio_button :ntc_importancy, "中"
        = f.label :中, class: "field--radio--midium"
        = f.radio_button :ntc_importancy, "低"
        = f.label :低, class: "field--radio--low"
      .field
        = f.label :緊急度：, class: "field--label"
        = f.label :必須, class: "field--must"
        %br
        %br
        = f.radio_button :ntc_emergency, "高"
        = f.label :高, class: "field--radio--high"
        = f.radio_button :ntc_emergency, "中"
        = f.label :中, class: "field--radio--midium"
        = f.radio_button :ntc_emergency, "低"
        = f.label :低, class: "field--radio--low"
      .field-content
        = f.label :内容：, class: "field-content--label"
        = f.label :必須, class: "field-content--must"
        %br
        = f.text_area :ntc_content, autofocus: true, autocomplete: "ntc_content", required: "true", class: "field-content--form--content"
      .field-file
        = f.label :添付ファイル：, class: "field-file--label"
        %br
        %br
        = f.file_field :ntc_upload_file, class: "field-file--form"
      .submit
        = f.submit "送信", class: "submit--btn"