config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  devise_scope :user do
    get 'new_assignment', to: 'users/registrations#new_assignment'
    post 'create_assignment', to: 'users/registrations#create_assignment'
  end
  root 'tops#index'
  resources :messages, only: [:index, :new, :create, :show]
  resources :circulations, only: [:index, :new, :create, :show]
  resources :notices, only: [:index, :new, :create, :show]
  resources :events
end

app/models/circulation.rb
class Circulation < ApplicationRecord
  belongs_to :user
  validates :cir_title, :cir_content, :cir_importancy, :cir_emergency, presence: true
  enum importancy:{
    高:1,中:2,低:3
  }, _prefix: :cir_importancy
  enum emergency:{
    高:1,中:2,低:3
  }, _prefix: :cir_emergency
end

app/controllers/circulations_controller.rb
class CirculationsController < ApplicationController
  def index
  end

  def new
    @circulation = Circulation.new
  end

  def create
    # circulation = {}
    if circulation_params[:cir_upload_file].present?
      circulation_params[:cir_upload_file].read
      circulation_params[:cir_upload_file_name] = circulation_params[:cir_upload_file].original_filename
      # circulation[:cir_upload_file_name] = "#{circulation_params[:cir_upload_file_name]}.#{circulation_params[:cir_upload_file].original_filename.split('.')[1]}"
    end
    @circulation = circulation.new(circulation_params)
    @circulation.save!
    redirect_to root_path
  end

  private
  
  def circulation_params
    params.require(:circulation).permit(:cir_title, :cir_content, :cir_importancy, :cir_emergency, :cir_upload_file_name, :cir_upload_file).merge(user_id: current_user.id)
  end
end

app/helpers/circulations_helper.rb
module CirculationsHelper
end

app/views/circulations/index.html.haml
.circulation-index
  .circulation-index__blank
  .circulation-index__btn
    =link_to new_circulation_path, class: "circulation-index__btn--sentence" do
      %i.far.fa-paper-plane
      新規回覧を作成
  .circulation-index__blank
  .circulation-index__list
    回覧一覧

app/views/circulations/new.html.haml
.circulation-new
  .circulation-new__first
    不要・不急のメッセージは控えましょう。
  .circulation-new__format
    = form_with model: @circulation, local: true, multiple: true do |f|
      .field
        = f.label :件名：, class: "field--label"
        = f.label :必須, class: "field--must"
        %br
        = f.text_field :cir_title, autofocus: true, autocomplete: "title", required: "true", class: "field--form--title"
      .field
        = f.label :重要度：, class: "field--label"
        = f.label :必須, class: "field--must"
        %br
        %br
        = f.radio_button :cir_importancy, "高"
        = f.label :高, class: "field--radio--high"
        = f.radio_button :cir_importancy, "中"
        = f.label :中, class: "field--radio--midium"
        = f.radio_button :cir_importancy, "低"
        = f.label :低, class: "field--radio--low"
      .field
        = f.label :緊急度：, class: "field--label"
        = f.label :必須, class: "field--must"
        %br
        %br
        = f.radio_button :cir_emergency, "高"
        = f.label :高, class: "field--radio--high"
        = f.radio_button :cir_emergency, "中"
        = f.label :中, class: "field--radio--midium"
        = f.radio_button :cir_emergency, "低"
        = f.label :低, class: "field--radio--low"
      .field-content
        = f.label :内容：, class: "field-content--label"
        = f.label :必須, class: "field-content--must"
        %br
        = f.text_area :content, autofocus: true, autocomplete: "content", required: "true", class: "field-content--form--content"
      .field-file
        = f.label :添付ファイル：, class: "field-file--label"
        %br
        %br
        = f.file_field :cir_upload_file, class: "field-file--form"
      .submit
        = f.submit "送信", class: "submit--btn"