config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  devise_scope :user do
    get 'new_assignment', to: 'users/registrations#new_assignment'
    post 'create_assignment', to: 'users/registrations#create_assignment'
  end
  root 'tops#index'
  resources :messages, only: [:index, :new, :create, :show]
  resources :circulations, only: [:index, :new, :create, :show]
  resources :notices, only: [:index, :new, :create, :show]
  resources :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    set_event
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render :index, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      set_event
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.destroy(event_params[:id])
    respond_to do |format|
      format.html { redirect_to events_url, notice: '正常に削除されました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :body, :start_date, :end_date).merge(user_id: current_user.id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
.events-new__format
  = form_for @event do |f|
    - if @event.errors.any?
      #error_explanation
        %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
        %ul
          - @event.errors.full_messages.each do |message|
            %li= message
    .field__title
      = f.label :件名：, class: "field__title--label"
      %br
      = f.text_field :title, autofocus: true, autocomplete: "title", required: "true", class: "field__title__field"
    .field__body
      = f.label :詳細：, class: "field__body--label"
      %br
      = f.text_area :body, autofocus: true, autocomplete: "title", required: "true", class: "field__body__area"
    .field__time
      .field__time__start
        = f.label :開始時刻：, class: "field__time__start--label"
        %br
        = f.datetime_select :start_date, {use_month_numbers: true}, autofocus: true, autocomplete: "title", required: "true", class: "field__time__start--dateselect"
      .field__time__end
        = f.label :終了時刻：, class: "field__time__end--label"
        %br
        = f.datetime_select :end_date, {use_month_numbers: true}, autofocus: true, autocomplete: "title", required: "true", class: "field__time__end--dateselect"
    .actions
      = f.submit '決定', class: "actions--btn"
    %br

app/views/events/edit.html.haml
.events-new
  %h1 予定を変更してください。

  = render 'form'
  .events-new--edit
    = link_to '予定の状況', @event, class: "events-new--edit--btn1"
    \|
    = link_to '戻る', events_path, class: "events-new--edit--btn2"

app/views/events/index.html.haml
.events
  -# %h1.events スケジュール一覧
  -# %table.events
  -#   %thead.events
  -#     %tr
  -#       %th 　予定
  -#       %th 詳細
  -#       %th 開始時刻
  -#       %th 終了時刻
  -#       %th
  -#       %th
  -#       %th

  -#   %tbody
  -#     - @events.each do |event|
  -#       %tr
  -#         %td= event.title
  -#         %td= event.body
  -#         %td= event.start_date
  -#         %td= event.end_date
  -#         %td= link_to 'Show', event
  -#         %td= link_to 'Edit', edit_event_path(event)
  -#         %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }
  %br
  %br
  .events__btn
    =link_to new_event_path, class: "events__btn--to_new" do
      予定を立てる
  #calendar.Calendar

app/views/events/new.html.haml
.events-new
  %h1 予定を入れてください。

  = render 'form'

  %br
  %br
  #calendar.Calendar

app/views/events/show.html.haml
.events-show
  %p#notice= notice
  .events-show__format
    %p.events-show__format--name
      = "#{@event.user.name}さん の予定"
    %p.events-show__format--title
      .events-show__format--title--label
        %b 件名：
      .events-show__format--title--form
        = @event.title
    %p.events-show__format--body
      .events-show__format--body--label
        %b 詳細：
      .events-show__format--body--form
        = @event.body
    .events-show__format--time
      %p.events-show__format--time--start
        %b 開始：
        = @event.start_date.strftime("%m/%d %H:%M")
      〜
      %p.events-show__format--time--end
        %b 終了：
        = @event.end_date.strftime("%m/%d %H:%M")
    %br
  %br
  -if user_signed_in? && current_user.id == @event.user_id
    .events-show__btn
      = link_to '編集', edit_event_path(@event), class: "events-show__btn--edit"
      \|
      = link_to '戻る', events_path, class: "events-show__btn--back"
      \|
      = link_to '削除', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "events-show__btn--destroy"
  -else
    .events-show__btn
      = link_to '戻る', events_path, class: "events-show__btn--back"